# Dendrite Configuration File
# Copy this file to dendrite.toml and adjust the settings for your environment

[main]
# Server listen address and port
# Can be overridden with --listen flag or DENDRITE_MAIN_LISTEN environment variable
listen = "127.0.0.1:3000"

# Storage quota limit across all directories
# Supports units: MB, GB, TB (e.g., "100GB", "1.5TB", "500MB")
# Leave empty for unlimited storage
# Can be overridden with --quota flag or DENDRITE_MAIN_QUOTA environment variable
quota = "100GB"

# JWT Authentication Configuration (optional)
# When JWT authentication is enabled, Dendrite operates in multi-tenant mode
# where directory access is controlled by JWT tokens.
# IMPORTANT: JWT mode and directory mappings are mutually exclusive!
[jwt_auth]
# JWT secret for token validation
# Must be at least 32 characters (256 bits) for security
# Can be overridden with --jwt-secret flag or DENDRITE_JWT_AUTH_JWT_SECRET environment variable
jwt_secret = ""

# Base directory for JWT mode
# All paths in JWT tokens are relative to this directory
# Required when jwt_secret is set
# Can be overridden with --base-dir flag or DENDRITE_JWT_AUTH_BASE_DIR environment variable
base_dir = ""

# Directory mappings (only used when JWT authentication is disabled).
# Each entry creates a virtual folder in the web interface
# Source must be an absolute path to an existing directory
# Virtual must start with / and be unique
# Can be extended with --dir flag (e.g., --dir /path:/virtual or --dir /path)

[[directories]]
# Path in filesystem exposed
source = "/home/user/documents"
# Virtual Path inside the filemanager
virtual = "/documents"

[[directories]]
source = "/home/user/videos"
virtual = "/videos"

[[directories]]
source = "/home/user/photos"
virtual = "/photos"

# Example with more directories:
# [[directories]]
# source = "/var/log/myapp"
# virtual = "/logs"
#
# [[directories]]
# source = "/etc/myapp/config"
# virtual = "/config"

# ============================================================================
# JWT Mode Configuration Example
# ============================================================================
# To enable JWT authentication mode, uncomment and configure the jwt_auth section:
#
# [jwt_auth]
# jwt_secret = "your-secret-key-must-be-at-least-32-characters-long"
# base_dir = "/var/files"
#
# With this configuration:
# - The [[directories]] sections above are ignored
# - All JWT token paths are relative to /var/files
# - Users can only access directories specified in their JWT tokens
#
# Example JWT payload:
# {
#   "directories": [
#     {"source": "user123/documents", "virtual": "/documents"},
#     {"source": "shared/public", "virtual": "/public"}
#   ],
#   "quota": "10GB",
#   "expires": "2025-12-31T23:59:59Z"
# }
#
# This would give access to:
# - /var/files/user123/documents (shown as /documents)
# - /var/files/shared/public (shown as /public)